#!/bin/sh

set -e

if [ ! -f "$1" ]; then
        echo "usage: $(basename "$0") FILE"
        exit 1
fi

. "$(readlink -f "$1")"

exec dsvpn \
	${MODE} \
	"$1".key \
	${HOST:-auto} \
	${PORT} \
	${DEV} \
	${LOCALTUNIP} \
	${REMOTETUNIP}
