[INCLUDES]
before = common.conf

[Definition]
_daemon = xray

#   2024/01/02 15:04:05 from 1.2.3.4:56789 rejected  proxy/vmess/inbound: invalid user
failregex = %(__prefix_line)s(?:\d{4}/\d{2}/\d{2} \d{2}:\d{2}:\d{2} )?from \[?<HOST>\]?:[0-9]{1,5} rejected\b

ignoreregex =

maxlines = 1
