[DEFAULT]
backend = systemd
banaction = nftables-multiport

[sshd]
enabled = true

[openvpn_tcp]
enabled = true
port = 65301
protocol = tcp
filter = openvpn
maxretry = 10
journalmatch = _SYSTEMD_UNIT=openvpn@tun0.service

[openvpn_udp]
enabled = true
port = 65301
protocol = udp
filter = openvpn
maxretry = 10
journalmatch = _SYSTEMD_UNIT=openvpn@tun1.service

[omradmin]
enabled = true
port = 65500
protocol = tcp
filter = omradmin
maxretry = 6
journalmatch = _SYSTEMD_UNIT=omr-admin.service

[xray]
enabled = true
port = 65248,65249,65250,65251,65252
protocol = tcp
filter = xray
maxretry = 6
journalmatch = _SYSTEMD_UNIT=xray.service

[v2ray]
enabled = true
port = 65228,65229,65230,65231
protocol = tcp
filter = v2ray
maxretry = 6
journalmatch = _SYSTEMD_UNIT=v2ray.service

[shadowsocks_go]
enabled = true
port = 65280
protocol = tcp
filter = shadowsocks-go
maxretry = 6
journalmatch = _SYSTEMD_UNIT=shadowsocks-go.service
