[INCLUDES]
before = common.conf

[Definition]
_daemon = v2ray

failregex = %(__prefix_line)s(?:\d{4}/\d{2}/\d{2} \d{2}:\d{2}:\d{2} )?from \[?<HOST>\]?:[0-9]{1,5} rejected\b

ignoreregex =

maxlines = 1
