[INCLUDES]
before = common.conf

[Definition]
_daemon = shadowsocks-go

failregex = %(__prefix_line)sFailed to complete handshake with client\b.*"clientAddress":\s*"\[?<HOST>\]?:[0-9]{1,5}"

ignoreregex =

maxlines = 1
