[INCLUDES]
before = common.conf

[Definition]
_daemon = (?:omradmin\.py|omr-admin)

failregex = ^%(__prefix_line)s(?:WARNING:?\s+)?(?:[\w.]+:[\w.]+:\d+ - )?omr-admin: authentication failure from <HOST>$

ignoreregex =

maxlines = 1
