#!/bin/sh

set -e

if [ ! -f "$1" ]; then
        echo "usage: $(basename "$0") FILE"
        exit 1
fi

. "$(readlink -f "$1")"

DEV="gt${HOST:+c}-udp-$(basename "$1")"

exec glorytun \
	bind $BIND $BIND_PORT \
	keyfile "$1".key \
	${DEV:+dev "$DEV"} \
	${HOST:+to "$HOST" "$PORT"} \
	${OPTIONS:+$OPTIONS}
