#!/bin/sh

set -e

if [ ! -f "$2" ]; then
        echo "usage: $(basename "$0") start FILE"
        exit 0
fi

. "$(readlink -f "$2")"

DEV="vx-$(basename "$2")"
PORT=${PORT:-4789}

if [ "$1" = "start" ]; then
        if [ -n "$(ip link show ${DEV} 2>/dev/null)" ]; then
                ip link del ${DEV} 2>&1 >/dev/null
        fi
        ip link add ${DEV} type vxlan id ${VNI} local ${LOCALIP} remote ${REMOTEIP} dstport ${PORT}
        if [ -n "${LOCALTUNIP}" ]; then
                ip addr add ${LOCALTUNIP} dev ${DEV}
        fi
        if [ -n "${LOCALTUNIP6}" ]; then
                ip -6 addr add ${LOCALTUNIP6} dev ${DEV}
        fi
        if [ -n "${MTU}" ]; then
                ip link set mtu ${MTU} dev ${DEV}
        fi
        ip link set ${DEV} up
fi
if [ "$1" = "stop" ]; then
        ip link del ${DEV}
fi
